import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { Poppins } from "next/font/google";
import axios from "axios";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export default function Home() {
  const handleSubmit = async (event) => {
    event.preventDefault();

    const { data } = await axios.post(
      "/api/submit",
      document.querySelector("#my-form"),
      {
        headers: {
          "Content-Type": "application/json",
        },
      }
    );
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${poppins.className}`}>
        <main className={styles.main}>
          <form onSubmit={handleSubmit} className={styles.form} id="my-form">
            <div className={styles.formGroup}>
              <label>Enter Email</label>
              <input type="email" name="email" />
            </div>
            <div className={styles.formGroup}>
              <label>Enter Password</label>
              <input type="password" name="password" />
            </div>
            <button type="submit">Submit</button>
          </form>
        </main>
      </div>
    </>
  );
}
