import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { Poppins } from "next/font/google";
import useStore from "@/store/useStore";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export default function Home() {
  const firstName = useStore((state) => state.firstName);
  const lastName = useStore((state) => state.lastName);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${poppins.className}`}>
        <main className={styles.main}>
          <ol>
            <li>
              Get started by editing <code>pages/index.js</code>.
            </li>
            <li>Save and see your changes instantly.</li>
          </ol>
          <FirstName />
          <LastName />
          <hr />
          <p>{firstName}</p>
          <p>{lastName}</p>
        </main>
      </div>
    </>
  );
}

function FirstName() {
  const updateFirstName = useStore((state) => state.updateFirstName);
  return (
    <>
      <label>FirstName</label>
      <input
        type="text"
        onChange={(ev) => {
          updateFirstName(ev.target.value);
        }}
      />
    </>
  );
}

function LastName() {
  const updateLastName = useStore((state) => state.updateLastName);

  return (
    <>
      <label>LastName</label>
      <input
        type="text"
        onChange={(ev) => {
          updateLastName(ev.target.value);
        }}
      />
    </>
  );
}
